### ISSUE TITLE
403

### ISSUE THREAD

**Issue by BlackTrace** [er28-0652/aio-anyrun#4]
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url=URL('wss://app.any.run/sockjs/926/8stjqo3q/websocket')

**Comment by er28-0652** [comment]
thank you for registering issue. 

403 response can be occurred when you send some invalid query data to ANY.RUN server. but it's tough to point the exact issue that you encountered. so could you please let me know more background information for more investigation? like;

- how did you use this script, command line? or as library?
- if as command line, please describe the parameters
- if as library, please describe the snippet code

**Comment by BlackTrace** [comment]
i solve this problem.Beacuse i run the script network come form china IP.i use proxy solve this problem.i will close this issue .thanks
